// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("WaveEngine.Components linux")]
[assembly: AssemblyCompanyAttribute("Wave Engine")]
[assembly: AssemblyDescriptionAttribute("linux")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Wave Engine 2015")]
[assembly: GuidAttribute("d4161402-ce18-494c-9f3a-cde368b1f964")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.9.11.24")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.9.11.24";
    }
}
